# -*- coding: utf-8 -*-
"""Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3XvDnlfdfkTv9S_2V7kZCvvMS9pcWai
"""

import streamlit as st

st.set_page_config(page_title="Welcome to SWISS PARENTERALS", layout="centered")

# 💡 Custom CSS for background and fonts
st.markdown("""
    <style>
        body {
            background: linear-gradient(to right, #f5f7fa, #c3cfe2);
        }
        h1 {
            color: #2c3e50;
            text-align: center;
        }
        .big-text {
            font-size: 18px;
            color: #34495e;
            text-align: center;
        }
    </style>
""", unsafe_allow_html=True)

# 🏠 Welcome Message
st.markdown("<h1>👋 Welcome to <span style='color:#2980b9'>SWISS</span></h1>", unsafe_allow_html=True)

st.markdown(
    """
    <div class="big-text">
    This is your centralized platform for production scheduling and performance dashboards.<br><br>
    Use the sidebar to:
    <ul style='text-align: left;'>
        <li>📦 <b>Schedule Batches</b> based on machine & material constraints</li>
        <li>📊 <b>Monitor Production KPIs</b> daily</li>
    </ul>
    </div>
    """,
    unsafe_allow_html=True
)

st.image("https://images.unsplash.com/photo-1581091012184-7f03a6cc0b6e", use_container_width=True)